service: bref-slack-bot

provider:
    name: aws
    stage: prod
    region: us-east-1
    environment:
        APP_ENV: production

functions:
    web:
        handler: public/index.php
        runtime: php-82-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        url: true
        brefLive: true

package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'

plugins:
  - ./vendor/bref/bref
  - '@bref.sh/live'
